---
- name: Notify PagerDuty of info events
  hosts: localhost
  tasks:
    - name: Send notification to PagerDuty
      community.general.pagerduty_alert:
        integration_key: "a0c9bf531775410ad08610a4dd7247d4"
        api_version: v2
        desc: "Failure event notification"
        source: "Ansible Playbook"
        state: "triggered"