---
- name: Notify PagerDuty of info events
  hosts: localhost
  tasks:
    - name: Check for update failure flag
      stat:
        path: /tmp/apt_update_failure.txt
      register: apt_update_failure_file

    - name: Send update notification to PagerDuty
      community.general.pagerduty_alert:
        integration_key: "a0c9bf531775410ad08610a4dd7247d4"
        api_version: v2
        desc: "Apt update Failed"
        source: "Ansible Playbook"
        state: "triggered"
      when: apt_update_failure_file.stat.exists

    - name: Remove update failure flag
      file:
        path: /tmp/apt_update_failure.txt
        state: absent
      when: apt_update_failure_file.stat.exists

    - name: Check for upgrade failure flag
      stat:
        path: /tmp/upgrade_failure.txt
      register: upgrade_failure_file

    - name: Send upgrade notification to PagerDuty
      community.general.pagerduty_alert:
        integration_key: "a0c9bf531775410ad08610a4dd7247d4"
        api_version: v2
        desc: "Apt upgrade Failed"
        source: "Ansible Playbook"
        state: "triggered"
      when: upgrade_failure_file.stat.exists

    - name: Remove upgrade failure flag
      file:
        path: /tmp/upgrade_failure.txt
        state: absent
      when: upgrade_failure_file.stat.exists

    - name: Check for reboot failure flag
      stat:
        path: /tmp/reboot_failure.txt
      register: reboot_failure_file

    - name: Send reboot notification to PagerDuty
      community.general.pagerduty_alert:
        integration_key: "a0c9bf531775410ad08610a4dd7247d4"
        api_version: v2
        desc: "Reboot failed"
        source: "Ansible Playbook"
        state: "triggered"
      when: reboot_failure_file.stat.exists

    - name: Remove reboot failure flag
      file:
        path: /tmp/reboot_failure.txt
        state: absent
      when: reboot_failure_file.stat.exists

