---
- name: Notify PagerDuty of info events
  hosts: localhost
  tasks:
    - name: Send notification to PagerDuty
      community.general.pagerduty:
        integration_key: "a0c9bf531775410ad08610a4dd7247d4"
        summary: "Info event notification"
        source: "Ansible Playbook"
        severity: "info"