---
- name: Configure passwordless sudo
  hosts: vm's
  become: yes
  tasks:
    - name: Ensure sudo package is installed
      apt:
        name: sudo
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure sudo package is installed
      yum:
        name: sudo
        state: present
      when: ansible_os_family == "RedHat"

    - name: Configure passwordless sudo for specified user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%{{ ansible_user }} ALL=\(ALL\) NOPASSWD: ALL'
        line: '%{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'